###*** YML file to define Producers and Consumers for Operations thro Kafka ***###
#*** BEGIN Kafka Configuration ***#
kafka:
  consumer:
    bootstrap: "10.24.2.83:9092"
    BE_TOPIC: BookingEngineNotification
    MDM_PRODUCT_TOPIC: MDM.PT.PRODUCT.PUB
    MDM_SUPPLIER_TOPIC: MDM.PT.SUPPLIER.PUB
    BE_MESSAGE_CONSUMER_GROUP: OperationsBookingNotificationsMessageConsumerGroupPT
    MDM_SUPPLIER_MESSAGE_CONSUMER_GROUP: OperationsMDMSupplierMessageConsumerGroupPT
    MDM_PRODUCT_MESSAGE_CONSUMER_GROUP: OperationsMDMProductMessageConsumerGroupPT
  producer:
    bootstrap: "10.24.2.83:9092"
    clientId: OperationsKafkaProducer
    email:
      topic: emailTopic
      enabled: true
    supplier-commercials:
      topic: MDM.PT.SUPPLIERCOMMERCIAL.PUB
      enabled: true
    client-commercials:
      topic: MDM.PT.CLIENTCOMMERCIAL.PUB
      enabled: true
    booking-notifications:
      topic: bookingNotifications
      enabled: true
#*** END Kafka Configuration  ***#
