###*** YML file to config Email Server Settings ***###
email:
  run-outbound: false
  run-inbound: false
  smtp:
    host: webmail.coxandkings.com
    port: 587
    username: smtp.capiot
    password: Sc#4!2PD
  inbound:
    host: webmail.coxandkings.com
    port: 110
    protocol : pop3
    folder : Inbox
    scheduler-config : 0 0 0/11 1/1 * ? *
    client-inbox: ops-inbound-client-dev
    client-password: PSN^5$e3
    customer-inbox: ops-inbound-customer-dev
    customer-password: PSN^5$e4
    supplier-inbox:  ops-inbound-supplier-dev
    supplier-password: PSN^5$e5
  temp-folder: "d:"
  mdm:
    b2c-client: ${mdm.client}/corpTraveller
    b2b-client: ${mdm.client}/clientB2B
    b2e-user: ${mdm.user-management}/user

sms:
  authId: MAMDI3YTK2MDEYMJVKOW
  authToken: YzQxOTVjNzg2OGZjZGVkNzhjYzY4NjZkNjVhMzY5
  send: http://bulkpush.mytoday.com//BulkSms/SingleMsgApi
  feedid: 208086
  senderid: CoxKings
  username: 9833988765
  password: wadmw
###*** END config of Email Server Settings ***###

#*** BEGIN EMAIL & ALERT API Service ***#
email_service:
  host: http://localhost
  port: ${server.port}

#** BEGIN Call Back URL for email accept and reject request ***#
call_back:
  host: ${operation.backend-url}
  port: ${server.port}
  base_url: ${operation.backend-url}
#** END Call Back URL for email accept and reject request ***#

alert_service:
  host:  ${operation.backend-url}
  port: ${server.port}
#*** BEGIN EMAIL & ALERT API Service ***#

