package com.coxandkings.travel.operations.consumer.listners;

public enum BookingListenerType {
    SERVICE_ORDER_AND_SUPPLIER_LIABILITY,
    THIRD_PARTY_VOUCHERS,
    NEW_SUPPLIER_FIRST_BOOKING,
    PRE_PAYMENT_TO_SUPPLIER,
    RECONFIRMATION_FIRST_BOOKING,
    TIME_LIMIT_EXPIRY_DATE,
    FLIGHT_TICKETING,
    FULL_CANCELLATION,
    MERGE_BOOKING,
    MANAGE_DOCUMENTATION,
    QC_MANAGEMENT,
    FILE_PROFITABILITY,
    RETRIEVE_ORDER_STATUS,
    FAILED_BOOKING,
    ALTERNATE_OPTIONS,
    FOREX_BOOKING;
}
